### ISSUE TITLE
Refactor: Home Section & Questions

### ISSUE THREAD

**Issue by adam-code-labx** [pinkary-project/pinkary.com#246]
### Proposed Improvement: Restructure Home Sections

First off, @tomloprod did a great job with this. 
I'm now suggesting some improvements that will span across a few different PRs.

### 1. HomeExplorer #245 

Currently, the home sections use blade views directly from routes. 
I propose introducing a new livewire page component called HomeExplorer to restructure these sections. 

#### What HomeExplorer Does:
- It groups home sections.
- It makes the home sections more dynamic and extendable.

#### Tasks:

- [X] Dynamic home sections
- [X] Update existing tests
- [ ] Update livewire layout component
- [ ] Extend tests

### Next Step: QuestionsWidget #247

This is the core feature of our app, and it's time for some enhancements. Currently the implementation of questions needs improvement. The objective of the upcoming PR is to consolidate all the question components into one component called QuestionsWidget.

#### Plan for QuestionsWidget:
- **Consolidation:** All questions Livewire components will be grouped into one component.
- **Data Isolation:** Ensure no data leakage as the container will be the only component interacting with Livewire.
- **Blade Components:** Questions will be represented as blade components to fully utilise the questions entities.
- **Single Responsibility:** Features like likes and pin views will be extracted into their own blade components.
- **Render-less Actions:** Actions will be render-less for example: InteractsWithQuestion trait.
- **Optimisation:** Reduces queries by almost 90%.

#### Tasks:

- [X] Questions widget component
- [X] Extract feeds to trait HasQuestionsFeed 
- [X] Restructure question item + components
- [ ] Setup and test traits for interacting with questions
- [ ] Tests

More to follow...
